/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package workdocs

import io.kotlintest.shouldBe
import io.kotlintest.shouldNotBe
import io.kotlintest.specs.StringSpec

class TestIntegrationInvokeWorkflow : StringSpec() {
    init {
        "Can Invoke Test Workflow" {
                main(arrayOf("ls"))

        }

    }
}